export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTTEXTFILES_SUBDIRS = \
	man2 \
	man3 \
	man4 \
	man5 \
	man8 \
	man9

include $(MakeInc_rule)
include $(MakeInc_dir)

