export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	idp.h  idp_var.h ns.h ns_error.h ns_if.h ns_pcb.h \
	sp.h spidp.h spp_debug.h spp_timer.h spp_var.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = netns

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netns


include $(MakeInc_rule)
include $(MakeInc_dir)


