#
# CDDL HEADER START
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the "License").  You may not use this file except
# in compliance with the License.
#
# You can obtain a copy of the license at
# src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing
# permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# HEADER in each file and include the License file at
# usr/src/OPENSOLARIS.LICENSE.  If applicable,
# add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your
# own identifying information: Portions Copyright [yyyy]
# [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#


CPPFLAGS=		-DUSE_GETHRTIME -D_REENTRANT

CFLAGS = -O $(extra_CFLAGS)

#
# These defines allow libmicro to be compiled against older Solaris
# releases by turning off the tests which don't work there.
#
# This is a little contorted-- UNAME_RELEASE is set as an environment
# variable for us by the invoking make process (see Makefile)-- it is
# the output of uname -r | sed 's/\./_/g'.
#
# We couldn't find any other gmake/unix make portable way to make this
# work.
#
ELIDED_BENCHMARKS_5_8=atomic cachetocache
ELIDED_BENCHMARKS_5_9=atomic

ELIDED_BENCHMARKS_CMN=cascade_flock

ELIDED_BENCHMARKS=$(ELIDED_BENCHMARKS_CMN) $(ELIDED_BENCHMARKS_$(UNAME_RELEASE))

include ../Makefile.com

NSLLIB=		-lnsl
SOCKLIB=	-lsocket
UCBLIB=		-lc -L/usr/ucblib -lucb -R/usr/ucblib
MATHLIB=	-lm

.KEEP_STATE:
