#!/bin/sh -x
#
# Copyright 2003 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
#
# script to make tarball... args are contents to be inserted
#

libmicro_version=`bin/getpid -V`
case $libmicro_version in
[0-9]*)
	;;
*)
	echo "ERROR: cannot determine libMicro version"
	exit 1
esac
dirname="libMicro-$libmicro_version"

here=`pwd`
target=$here/libMicro.tar
tmpdir=/private/tmp/libmicro.$$
mkdir -p $tmpdir/$dirname
cp $* $tmpdir/$dirname
cd $tmpdir
tar cvf $target $dirname
cd $here
rm -rf $tmpdir
