export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir

include $(MakeInc_cmd)
include $(MakeInc_def)

EXPORT_FILES = xnupost.h ktest.h

EXPORT_MI_LIST = ${EXPORT_FILES}

EXPORT_MI_DIR = tests

INSTALL_KF_MI_LCL_LIST =
INSTALL_KF_MI_LIST =

include $(MakeInc_rule)
include $(MakeInc_dir)
