#
# CDDL HEADER START
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the "License").  You may not use this file except
# in compliance with the License.
#
# You can obtain a copy of the license at
# src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing
# permissions and limitations under the License.
#
# When distributing Covered Code, include this CDDL
# HEADER in each file and include the License file at
# usr/src/OPENSOLARIS.LICENSE.  If applicable,
# add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your
# own identifying information: Portions Copyright [yyyy]
# [name of copyright owner]
#
# CDDL HEADER END
#

#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# ident	"@(#)Makefile.Darwin	1.5	05/08/04 SMI"
#

SDKROOT ?= /
Product=$(shell tconf --product)
Embedded=$(shell tconf --test TARGET_OS_EMBEDDED)

ifeq "$(Embedded)" "YES"
SDKPATH = $(shell xcodebuild -sdk "$(SDKROOT)" -version Path)
CFLAGS += -isysroot $(SDKPATH)
EmbeddedOS=yes
endif

CC = $(shell xcrun -sdk "$(SDKROOT)" -find gcc)
#NOPIC=	-mdynamic-no-pic
ARCH= i386

ifeq "$(strip $(ARCH))" "fat"
ARCH_FLAG=      -arch i386 -arch x86_64 
else
ARCH_FLAG=      -arch $(ARCH)
endif

### OPT_FLAG value was modified from '-g' to '-Os' as part of the fix for radar 7508837
OPT_FLAG=	-Os
SEMOP_FLAG=	-DUSE_SEMOP
ifeq "$(Embedded)" "YES"
SEMOP_FLAG= 
endif

###
###CFLAGS=		-Os -DUSE_SEMOP -fno-builtin $(NOPIC) $(ARCH_FLAG) -Wall
###extra_CFLAGS=	-Os -DUSE_SEMOP -fno-builtin $(NOPIC) $(ARCH_FLAG) -Wall
###
CFLAGS+=		$(OPT_FLAG) $(SEMOP_FLAG) -DUSE_GETHRTIME -fno-builtin $(NOPIC) $(ARCH_FLAG) -Wall

ifeq "$(Embedded)" "YES"
#CFLAGS+=		 $(OPT_FLAG) -DUSE_GETHRTIME -fno-builtin $(NOPIC) $(ARCH_FLAG) -Wall
CFLAGS+= -g -I $(SDKPATH)/System/Library/Frameworks/System.framework/Versions/B/PrivateHeaders/ -F/AppleInternal/Library/Frameworks/ $(MORECFLAGS)
endif

extra_CFLAGS=	$(OPT_FLAG) $(SEMOP_FLAG) -DUSE_GETHRTIME -fno-builtin $(NOPIC) $(ARCH_FLAG) -Wall
CPPFLAGS=		$(SEMOP_FLAG) -D_REENTRANT -Wall
MATHLIB=	-lm

ELIDED_BENCHMARKS=	\
	cachetocache	\
	atomic	\
	getcontext	\
	setcontext	\
	fork	\
	exit	\
	connection


include ../Makefile.com.Darwin
