export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \
	crypto \
	dev \
	hfs \
	isofs \
	libkern \
	machine \
	miscfs \
	net \
	netat \
	netinet \
	netinet6 \
	netkey \
	nfs \
	sys \
	ufs \
	vfs

INSTINC_SUBDIRS_PPC = \
	ppc 

INSTINC_SUBDIRS_I386 = \
	i386 

EXPINC_SUBDIRS = \
	crypto \
	dev \
	hfs \
	isofs \
	libkern \
	machine \
	miscfs \
	net \
	netat \
	netinet \
	netinet6 \
	netkey \
	nfs \
	sys \
	ufs \
	vfs \
	vm

EXPINC_SUBDIRS_PPC = \
	ppc 

EXPINC_SUBDIRS_I386 = \
	i386 

SETUP_SUBDIRS = 	\
	conf

COMP_SUBDIRS = 	\
	conf

INST_SUBDIRS =	\

INSTMAN_SUBDIRS = \
	man

include $(MakeInc_rule)
include $(MakeInc_dir)


