.\"	$NetBSD: getfsstat.2,v 1.6 1995/06/29 11:40:44 cgd Exp $
.\"
.\" Copyright (c) 1989, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)getfsstat.2	8.1 (Berkeley) 6/9/93
.\"
.Dd Oct 28, 2008
.Dt GETFSSTAT 2
.Os
.Sh NAME
.Nm getfsstat
.Nd get list of all mounted file systems
.Sh SYNOPSIS
.Fd #include <sys/param.h>
.Fd #include <sys/ucred.h>
.Fd #include <sys/mount.h>
.Ft int
.Fn getfsstat "struct statfs *buf" "int bufsize" "int flags"
.Sh TRANSITIIONAL SYNOPSIS (NOW DEPRECATED)
.Ft int
.br
.Fn getfsstat64 "struct statfs64 *buf" "int bufsize" "int flags" ;
.Sh DESCRIPTION
The
.Fn getfsstat
function returns information about all mounted file systems.
The
.Fa buf
argument is a pointer to an array of
.Fa statfs
structures (see 
.Xr statfs 2 ) .
As
.Xr statfs 2
indicates, the structure is defined differently depending on
whether the macro _DARWIN_FEATURE_64_BIT_INODE is defined (see
.Xr stat 2
for more information on this macro).
.Pp
Fields that are undefined for a particular file system are set to -1.
The buffer is filled with an array of
.Fa statfs
structures, one for each mounted file system
up to the size specified by
.Fa bufsize .
.Pp
If
.Fa buf
is given as NULL,
.Fn getfsstat
returns just the number of mounted file systems.
.Pp
If
.Fa flags
is set to
.Dv MNT_NOWAIT ,
.Fn getfsstat
will directly return the information retained in the kernel
to avoid delays caused by waiting for updated information from
a file system that is perhaps temporarily unable to respond.
Some of the information returned may be out of date, however; if
.Fa flags
is set to
.Dv MNT_WAIT
or
.Dv MNT_DWAIT
instead,
.Fn getfsstat
will request updated information from each mounted filesystem before
returning.
.Sh RETURN VALUES
Upon successful completion, the number of 
.Fa statfs
structures is returned.
Otherwise, -1 is returned and the global variable
.Va errno
is set to indicate the error.
.Sh ERRORS
.Fn getfsstat
fails if one or more of the following are true:
.Bl -tag -width Er
.It Bq Er EFAULT
The
.Fa buf
argument points to an invalid address.
.It Bq Er EIO
An
.Tn I/O
error occurred while reading from or writing to the file system.
.El
.Sh TRANSITIONAL DESCRIPTION (NOW DEPRECATED)
The
.Fn getfsstat64
routine is equivalent to the default
.Fn getfstat
(when
.Dv _DARWIN_FEATURE_64_BIT_INODE
is defined), so there is no longer any reason to use it (it will be removed
in the future).
.Sh SEE ALSO
.Xr stat 2 ,
.Xr statfs 2 ,
.Xr fstab 5 ,
.Xr mount 8
.Sh HISTORY
The
.Fn getfsstat
function first appeared in 4.4BSD.
