export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \
	devfs \
	fifofs \
	specfs \
	union

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \
	devfs \
	fifofs \
	specfs

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

SETUP_SUBDIRS = 	\

COMP_SUBDIRS = 	\

INST_SUBDIRS =	\


include $(MakeInc_rule)
include $(MakeInc_dir)


