export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	ah.h esp.h icmp6.h in6.h in6_gif.h in6_ifattach.h in6_pcb.h \
	in6_prefix.h in6_var.h ip6.h ip6_fw.h ip6_mroute.h ip6_var.h \
	ip6protosw.h ipcomp.h ipsec.h mip6.h mip6_common.h mld6_var.h \
	natpt_defs.h natpt_list.h natpt_log.h natpt_soctl.h natpt_var.h \
	nd6.h pim6.h pim6_var.h udp6.h udp6_var.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = netinet6

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netinet6


include $(MakeInc_rule)
include $(MakeInc_dir)


