export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir

include $(MakeInc_cmd)
include $(MakeInc_def)

INSTTEXTFILES_SUBDIRS = scripts

INSTTEXTFILES_SUBDIRS_X86_64 = scripts
INSTTEXTFILES_SUBDIRS_X86_64H = scripts
INSTTEXTFILES_SUBDIRS_ARM = scripts
INSTTEXTFILES_SUBDIRS_ARM64 = scripts

include $(MakeInc_rule)
include $(MakeInc_dir)
