export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	argo_debug.h clnl.h clnp.h clnp_stat.h cltp_var.h cons.h \
	cons_pcb.h eonvar.h esis.h iso.h iso_errno.h iso_pcb.h  \
	iso_snpac.h iso_var.h tp_clnp.h tp_events.h tp_ip.h tp_meas.h \
	tp_param.h tp_pcb.h tp_seq.h tp_stat.h tp_states.h tp_timer.h \
	tp_tpdu.h tp_trace.h tp_user.h tuba_table.h


INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = netiso

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netiso


include $(MakeInc_rule)
include $(MakeInc_dir)


