export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	dll.h hd_var.h hdlc.h llc_var.h pk.h pk_var.h \
	x25.h x25_sockaddr.h x25acct.h x25err.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = netccitt

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netccitt


include $(MakeInc_rule)
include $(MakeInc_dir)


