export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = pexpert
INSTINC_SUBDIRS_I386 = pexpert
INSTINC_SUBDIRS_X86_64 = pexpert
INSTINC_SUBDIRS_ARM = pexpert


EXPINC_SUBDIRS = pexpert
EXPINC_SUBDIRS_I386 = pexpert
EXPINC_SUBDIRS_X86_64 = pexpert
EXPINC_SUBDIRS_ARM = pexpert


SETUP_SUBDIRS =

COMP_SUBDIRS = 	\
	conf

INST_SUBDIRS =	\


include $(MakeInc_rule)
include $(MakeInc_dir)


