ifdef BASEDSTROOT
override DSTROOT = $(BASEDSTROOT)
endif

# the xnu build system will only ever call us with the default target
.DEFAULT_GOAL := install

install:
	mkdir -p $(DSTROOT)/AppleInternal


