export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \
	arpa \
	protocols

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	ar.h bitstring.h c.h ctype.h db.h    dirent.h disktab.h err.h errno.h \
	fcntl.h fnmatch.h fsproperties.h fstab.h fts.h glob.h grp.h kvm.h limits.h locale.h \
	math.h  memory.h mpool.h ndbm.h    netdb.h  nlist.h paths.h  pwd.h ranlib.h \
	regex.h regexp.h   rune.h  runetype.h setjmp.h semaphore.h sgtty.h signal.h stab.h \
	stddef.h stdio.h stdlib.h string.h strings.h struct.h sysexits.h syslog.h \
	tar.h termios.h time.h ttyent.h tzfile.h unistd.h util.h utime.h utmp.h vis.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = 

EXPORT_MI_LIST	= stddef.h

EXPORT_MI_DIR =


include $(MakeInc_rule)
include $(MakeInc_dir)


