export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

ALL_SUBDIRS = 

INSTINC_SUBDIRS = 

INSTINC_SUBDIRS_PPC = 

INSTINC_SUBDIRS_I386 = 

EXPINC_SUBDIRS = 

EXPINC_SUBDIRS_PPC =  

EXPINC_SUBDIRS_I386 = 

COMP_SUBDIRS = 

INST_SUBDIRS =	

INSTALL_DATA_LIST= \
	System.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/AppleNMI.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/ApplePlatformFamily.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/BSDKernel.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/IOADBFamily.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/IOKit.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/IONVRAMFamily.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/IOSystemManagement.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/Libkern.kext/Contents/Info.plist \
	System.kext/Contents/PlugIns/Mach.kext/Contents/Info.plist

INSTALL_DATA_DIR= \
	/System/Library/Extensions/

INSTMAN_SUBDIRS = 

include $(MakeInc_rule)
include $(MakeInc_dir)
