export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

SETUP_SUBDIRS = 	\

COMP_SUBDIRS = 	\

INST_SUBDIRS =	\

DATAFILES = appletalk.h atp.h asp.h at_pcb.h at_var.h aurp.h \
	    debug.h ddp.h ep.h lap.h nbp.h pap.h sysglue.h zip.h \
	    adsp.h adsp_internal.h \
	    at_pat.h  at_snmp.h at_aarp.h at_ddp_brt.h \
	    routing_tables.h rtmp.h

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = netat

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = netat

include $(MakeInc_rule)
include $(MakeInc_dir)


