export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir

include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = 

INSTINC_SUBDIRS_PPC = 

INSTINC_SUBDIRS_I386 = 

INSTINC_SUBDIRS_X86_64 = 

INSTINC_SUBDIRS_ARM = 

EXPINC_SUBDIRS = ${INSTINC_SUBDIRS}

EXPINC_SUBDIRS_PPC = ${INSTINC_SUBDIRS_PPC}

EXPINC_SUBDIRS_I386 = ${INSTINC_SUBDIRS_I386}

EXPINC_SUBDIRS_X86_64 = ${INSTINC_SUBDIRS_X86_64}

EXPINC_SUBDIRS_ARM = ${INSTINC_SUBDIRS_ARM}

DATAFILES = \
          OSArray.h \
          OSBoolean.h \
          OSCollection.h \
          OSCollectionIterator.h \
          OSContainers.h \
          OSCPPDebug.h \
          OSData.h \
          OSDictionary.h \
          OSEndianTypes.h \
          OSIterator.h \
          OSKext.h \
          OSLib.h \
          OSMetaClass.h \
          OSNumber.h \
          OSObject.h \
          OSOrderedSet.h \
          OSSerialize.h \
          OSSet.h \
          OSString.h \
          OSSymbol.h \
          OSUnserialize.h

INSTALL_MD_LIST	=

INSTALL_MD_DIR = libkern/c++

EXPORT_MD_LIST	= ${DATAFILES}

EXPORT_MD_DIR = libkern/c++

include $(MakeInc_rule)
include $(MakeInc_dir)


