export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

MIG_DEFS =	\

MIG_HDRS = \

DATAFILES = \

MIGINCLUDES = \

EXPORT_MI_LIST	= ${DATAFILES} ${_MIG_HDRS_} ${MIGINCLUDES}

EXPORT_MI_DIR = ddb

.ORDER: ${_MIG_HDRS_} ${MIGINCLUDES}

include $(MakeInc_rule)
include $(MakeInc_dir)


