export MakeInc_cmd=${SRCROOT}/makedefs/MakeInc.cmd
export MakeInc_def=${SRCROOT}/makedefs/MakeInc.def
export MakeInc_rule=${SRCROOT}/makedefs/MakeInc.rule
export MakeInc_dir=${SRCROOT}/makedefs/MakeInc.dir


include $(MakeInc_cmd)
include $(MakeInc_def)

INSTINC_SUBDIRS = \

INSTINC_SUBDIRS_PPC = \

INSTINC_SUBDIRS_I386 = \

EXPINC_SUBDIRS = \

EXPINC_SUBDIRS_PPC = \

EXPINC_SUBDIRS_I386 = \

DATAFILES = \
	acct.h attr.h buf.h callout.h cdefs.h cdio.h chio.h clist.h conf.h \
	dir.h dirent.h disklabel.h disktab.h dkbad.h dkstat.h dmap.h domain.h \
	errno.h ev.h exec.h fcntl.h file.h filedesc.h filio.h gmon.h ioccom.h ioctl.h \
	ioctl_compat.h ipc.h kernel.h kern_event.h ktrace.h loadable_fs.h lock.h lockf.h mach_swapon.h malloc.h \
	kdebug.h linker_set.h md5.h\
	mbuf.h mman.h mount.h msgbuf.h mtio.h namei.h netport.h param.h paths.h \
	proc.h protosw.h ptrace.h queue.h random.h reboot.h resource.h resourcevar.h \
	select.h semaphore.h shm.h signal.h signalvar.h socket.h socketvar.h sockio.h stat.h \
	syscall.h sysctl.h syslimits.h syslog.h systm.h termios.h  time.h \
	timeb.h times.h tprintf.h trace.h tty.h  ttychars.h ttycom.h \
	ttydefaults.h ttydev.h  types.h ubc.h ucred.h uio.h un.h unistd.h unpcb.h \
	user.h utfconv.h utsname.h ux_exception.h vadvise.h vcmd.h  version.h vlimit.h \
	vm.h vmmeter.h vmparam.h vnode.h vnode_if.h vstat.h wait.h 

INSTALL_MI_LIST	= ${DATAFILES}

INSTALL_MI_DIR = sys

EXPORT_MI_LIST	= ${DATAFILES}

EXPORT_MI_DIR = sys


include $(MakeInc_rule)
include $(MakeInc_dir)


